// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MnemosAPI.Models;

public partial class Scale
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}