// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MnemosAPI.Models;

public partial class Skill
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public int AreaId { get; set; }

    public int ScaleId { get; set; }

    public virtual Area Area { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual Scale Scale { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public static implicit operator int(Skill v)
    {
        throw new NotImplementedException();
    }
}