INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1001, 'Java 6', 'Versione 6 del linguaggio Java', 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1002, 'Java 7/8/9', 'Linguaggio Java con Stream API, Future, Optional, Lambda', 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1003, 'Java 10+', 'Le ultime versioni di Java: nuove funzionalità per Pattern Matching, Record, nuovo switch, ecc.', 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1004, 'C#', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1005, 'Python', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1006, 'Javascript', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1007, 'Typescript', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1008, 'COBOL', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1009, 'C/C++', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1010, 'Kotlin', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1011, 'Swift', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1012, 'Objective-C', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1013, 'Dart', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1014, 'PHP', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1015, 'Go', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1016, 'Scala', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1017, 'R', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1018, 'SQL', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1019, 'PL/SQL', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1020, 'T-SQL', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1021, 'ABAP', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1022, 'Groovy', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1023, 'Ruby', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1024, 'HTML', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1025, 'CSS', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1026, 'XML', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1027, 'XSL', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1028, 'Bash scripting', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1029, 'PowerShell scripting', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1030, 'VB.NET', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1031, 'VBScript', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1032, 'F#', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (1033, 'XPATH', NULL, 'HARD', 1, 1);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2001, 'Spring Core', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2002, 'Spring Boot', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2003, 'Spring Security', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2004, 'Spring Batch', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2005, 'Spring Cloud', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2006, 'Spring Data', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2007, 'Spring LDAP', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2008, 'Spring Statemachine', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2009, 'JSF', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2010, 'PrimeFaces', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2011, 'IceFaces', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2012, 'Struts', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2013, 'JPA', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2014, 'Hibernate', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2015, 'EJB', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2016, 'JAX-RS', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2017, 'JAX-WS', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2018, 'JAXB', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2019, 'JSON-P', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2020, 'JSON-B', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2021, 'JMS', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2022, 'Servlet', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2023, 'CDI', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2024, 'JSP', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2025, 'EL', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2026, 'JNDI', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2027, 'Bean Validation', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2028, 'Quarkus', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2029, 'Camel', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2030, 'JackRabbit', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2031, 'Vertx', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2032, 'Lucene', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2033, 'Log4J', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2034, 'Apache POI', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2035, 'JCR', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2036, 'Apache Sling', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2037, 'SolR', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2038, 'Tapestry', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2039, 'Velocity', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2040, 'GWT', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2041, 'iBatis', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2042, 'Jsoup', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2043, 'JUnit', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2044, 'Quartz', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2045, 'SLF4J', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2046, 'Selenium', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2047, 'Jasper Reports', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2048, 'TestNG', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2049, 'Thymeleaf', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2050, 'Vaadin', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2051, 'Swing', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2052, 'JavaFx', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2053, 'Maven', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2054, 'Gradle', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2055, 'Ant', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2056, 'JMeter', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2057, 'Surefire', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (2058, 'RestAssured', NULL, 'HARD', 2, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3001, 'Entity Framework Core', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3002, 'Dapper', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3003, 'NHibernate', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3004, 'SignalR', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3005, 'MediatR', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3006, 'FluentValidation', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3007, 'Moq', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3008, 'FluentAssertion', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3009, 'xUnit', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3010, 'NUnit', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3011, 'ASP.NET Core', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3012, 'Blazor', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3013, 'Serilog', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3014, '.NET Framework', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3015, '.NET Core', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3016, 'WPF', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3017, 'ASP.NET', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3018, 'Entity Framework', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3019, 'Polly', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3020, 'EPPlus', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3021, 'IdentityServer', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3022, 'IdentityModel', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3023, 'NuGet', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3024, 'Ocelot', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (3025, 'MSTest', NULL, 'HARD', 3, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4001, 'Angular.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4002, 'Angular 2+', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4003, 'React.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4004, 'Vue.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4005, 'Backbone.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4006, 'Chart.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4007, 'D3.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4008, 'Express', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4009, 'SenchaJs', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4010, 'jQuery', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4011, 'Lodash', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4012, 'Mustache', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4013, 'Loopback', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4014, 'PDFjs', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4015, 'Polymer', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4016, 'Redux', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4017, 'Svelte', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4018, 'Bootstrap', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4019, 'Material', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4020, 'Angular Universal', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4021, 'Npm', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4022, 'Gulp', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4023, 'Grunt', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4024, 'Webpack', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4025, 'Koa', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4026, 'Puppeteer', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4027, 'Electron', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4028, 'Mocha', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4029, 'Jest', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4030, 'Jasmine', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4031, 'Sequelize', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4032, 'Mongoose', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4033, 'Moment', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4034, 'Apollo', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4035, 'TypeORM', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4036, 'Babel', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4037, 'ESLint', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4038, 'Anime.js', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4039, 'Meteor', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4040, 'Nest', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4041, 'Newman', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (4042, 'WebDriverIO', NULL, 'HARD', 4, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5001, 'Android Layouts', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5002, 'Jetpack Navigation', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5003, 'Android Activity', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5004, 'Android Fragment', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5005, 'Room', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5006, 'RecyclerView', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5007, 'LiveData', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5008, 'Jetpack ViewModel', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5009, 'Compose', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5010, 'Retrofit', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5011, 'Picasso', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5012, 'Glide', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5013, 'CameraX', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5014, 'Paging', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5015, 'Hilt', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5016, 'Dagger', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5017, 'WearOS', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5018, 'RxJava', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5019, 'Espresso', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5020, 'Roboelectric', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5021, 'Timber', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5022, 'OkHttp', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5023, 'Realm', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5024, 'Stetho', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5025, 'Coroutines', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5026, 'Flow', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5027, 'Android Services', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5028, 'Jetpack WorkManager', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5029, 'Koin', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5030, 'Android Flavours', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5031, 'get_it', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5032, 'injectable', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5033, 'injectable_generator', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5034, 'fpdart o dartz', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5035, 'intl', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5036, 'json_annotation', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5037, 'json_serializable', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5038, 'flutter_lints', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5039, 'build_runner', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5040, 'retrofit', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5041, 'dio', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5042, 'dio_cache_interceptor', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5043, 'bloc', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5044, 'provider', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5045, 'mobx', '', 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5046, 'moor', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5047, 'secure_storage', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5048, 'shared_preferences', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5049, 'firebase_core', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5050, 'firebase_messaging', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5051, 'local_notification', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5052, 'huawei_push', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5053, 'routermaster', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5054, 'auto_route', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5055, 'easy_localization', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5056, 'pigeon', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5057, 'UIViewController Life Cycle', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5058, 'UITableView Datasource', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5059, 'UICollectionView Grid/Custom Layout', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5060, 'UIControl subclassing', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5061, 'Custom UINavigationController', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5062, 'UITabBarController', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5063, 'UISplitController', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5064, 'Segues and Unwind segues', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5065, 'URLRequest, URLSession, URLComponents', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5066, 'XConfig', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5067, 'Codable', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5068, 'Cocoapod', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5069, 'Swift Package Manager', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5070, 'OSLog', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5071, 'Core Data', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5072, 'iOS FileManager', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5073, 'OperationQueue', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5074, 'iOS Dispatch', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5075, 'iOS Background modes', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5076, 'iCloud capabilities', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5077, 'SwiftUI', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5078, 'iOS Widget and Watch extensions', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5079, 'In-App purchase', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5080, 'Sign in with Apple', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5081, 'Xamarin', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5082, 'Ionic', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5083, 'React Native', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (5084, 'Capacitor', NULL, 'HARD', 5, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6001, 'Tensorflow', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6002, 'Scikit-learn', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6003, 'NumPy', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6004, 'PyTorch', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6005, 'Keras', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6006, 'Pandas', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6007, 'Matplotlib', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6008, 'Hadoop', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6009, 'Spark', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6010, 'Flink', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6011, 'Hive', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6012, 'Pig', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6013, 'Impala', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6014, 'Qlik View', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6015, 'Qlik Sense', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6016, 'Tableau', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6017, 'Power BI', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6018, 'Grafana', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6019, 'Drill', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6020, 'Sqoop', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6021, 'Flume', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6022, 'Oozie', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6023, 'Ambari', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6024, 'SAP Business Objects', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6025, 'Beam', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6026, 'Airflow', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6027, 'KubeFlow', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6028, 'Talend', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6029, 'Splunk', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6030, 'Kibana', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (6031, 'Pentaho', NULL, 'HARD', 6, 2);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7001, 'MySQL', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7002, 'PostgreSQL', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7003, 'Oracle', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7004, 'SQL Server', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7005, 'SQLite', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7006, 'Realm', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7007, 'MongoDB', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7008, 'Cassandra', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7009, 'Hbase', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7010, 'Neo4J', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7011, 'Sap Hana', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7012, 'CouchDB', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7013, 'OrientDB', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7014, 'Redis', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7015, 'Ignite', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7016, 'Firebird', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (7017, 'MariaDB', NULL, 'HARD', 7, 3);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8001, 'App Engine', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8002, 'Compute Engine', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8003, 'GKE', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8004, 'Cloud Functions', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8005, 'Cloud Run', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8006, 'Cloud Storage', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8007, 'Cloud SQL', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8008, 'Bigtable', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8009, 'Spanner', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8010, 'Datastore', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8011, 'VPC', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8012, 'Cloud Load Balancing', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8013, 'Cloud Armor', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8014, 'Cloud CDN', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8015, 'Cloud Interconnect', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8016, 'Cloud DNS', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8017, 'BigQuery', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8018, 'Dataflow', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8019, 'Dataproc', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8020, 'Composer', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8021, 'Datalab', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8022, 'Dataprep', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8023, 'Pub/Sub', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8024, 'Data Studio', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8025, 'AutoML', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8026, 'Machine Learning Engine', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8027, 'Dialogflow', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8028, 'Cloud Shell', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8029, 'Cloud Identity', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8030, 'IAM', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8031, 'IAP', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8032, 'KMS', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8033, 'IoT Core', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8034, 'Apigee', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8035, 'Cloud Endpoints', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8036, 'Anthos', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8037, 'Vertex AI', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8038, 'Istio', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8039, 'Cloud Logging', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8040, 'Firebase Realtime Database', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8041, 'Firebase Auth', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8042, 'Firestore', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8043, 'Firebase Storage', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8044, 'Firebase Functions', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8045, 'Firebase Messaging', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8046, 'Firebase Remote Config', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8047, 'Firebase ML', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8048, 'Firebase Hosting', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8049, 'Crashlytics', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (8050, 'Workflows', NULL, 'HARD', 8, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9001, 'EC2', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9002, 'Lightsail', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9003, 'ECS', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9004, 'ECR', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9005, 'EKS', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9006, 'Fargate', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9007, 'Lambda', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9008, 'Beanstalk', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9009, 'ELB', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9010, 'Aurora', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9011, 'RDS', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9012, 'Redshift', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9013, 'DynamoDB', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9014, 'Elasticache', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9015, 'MemoryDB', '', 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9016, 'DocumentDB', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9017, 'EventBridge', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9018, 'SQS', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9019, 'SNS', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9020, 'API Gateway', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9021, 'AppSync', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9022, 'S3', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9023, 'EFS', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9024, 'EBS', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9025, 'Cognito', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9026, 'Config', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9027, 'KMS', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9028, 'EMR', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9029, 'Athena', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9030, 'Kinesis', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9031, 'QuickSight', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9032, 'Glue DataBrew', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9033, 'MSK', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9034, 'Lake Formation', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9035, 'SageMaker', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9036, 'CloudWatch', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9037, 'Amplify', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9038, 'IoT Core', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9039, 'IoT Device management', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9040, 'IoT Events', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9041, 'CloudFormation', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9042, 'VPC', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9043, 'Transit Gateway', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9044, 'AppMesh', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9045, 'CloudFront', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9046, 'Route 53', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (9047, 'Shield', NULL, 'HARD', 9, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10001, 'DataBricks', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10002, 'Synapse Analytics', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10003, 'Data Factory', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10004, 'Data Catalog', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10005, 'Data Lake Analytics', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10006, 'HDInsight', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10007, 'Azure Active Directory', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10008, 'Event Hubs', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10009, 'Disk Storage', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10010, 'BLOB Storage', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10011, 'Files', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10012, 'Azure Machine Learning', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10013, 'Cognitive Search', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10014, 'Cognitive Services', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10015, 'Computer Vision', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10016, 'Face API', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10017, 'Speech to text', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10018, 'Text to speech', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10019, 'App Service', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10020, 'Batch', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10021, 'Cloud Services', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10022, 'Virtual Machines', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10023, 'AKS', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10024, 'Functions', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10025, 'Service Fabric', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10026, 'Container Instances', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10027, 'Container Registry', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10028, 'Cache for Redis', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10029, 'Cosmos DB', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10030, 'Database for MariaDB', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10031, 'Database for MySQL', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10032, 'Database for PostgreSQL', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10033, 'SQL', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10034, 'App Configuration', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10035, 'Pipelines', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10036, 'DevOps', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10037, 'Artifacts', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10038, 'Azure Boards', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10039, 'API Management', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10040, 'Event Grid', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10041, 'Service Bus', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10042, 'Logic Apps', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10043, 'IoT Hub', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10044, 'IoT Central', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10045, 'IoT Edge', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10046, 'Monitor', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10047, 'Purview', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10048, 'Application Gateway', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10049, 'DNS', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10050, 'Bastion', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10051, 'Firewall', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10052, 'ExpressRoute', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10053, 'Load Balancer', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10054, 'Front Door', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10055, 'Sentinel', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10056, 'Key Vault', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10057, 'SignalR Service', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10058, 'Azure CLI', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (10059, 'ARM Template', NULL, 'HARD', 10, 4);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11001, 'Windows Administration', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11002, 'Linux Administration', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11003, 'MacOS Administration', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11004, 'Logstash', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11005, 'DataDog', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11006, 'Rancher', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11007, 'Zookeeper', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11008, 'Mesos', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11009, 'Nagios', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11010, 'SonarQube', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11011, 'Spinnaker', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11012, 'Postman', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11013, 'SoapUI', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11014, 'Kubernetes', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11015, 'Docker', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11016, 'Helm', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11017, 'Terraform', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11018, 'Ansible', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11019, 'Chef', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11020, 'Puppet', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11021, 'Jenkins', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11022, 'Travis', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11023, 'GlassFish', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11024, 'Wildfly', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11025, 'Nginx', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11026, 'Jboss', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11027, 'Apache Web Server', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11028, 'IIS', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11029, 'WebSphere', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (11030, 'Tomcat', NULL, 'HARD', 11, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12001, 'Kafka', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12002, 'ActiveMQ', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12003, 'RabbitMQ', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12004, 'ElasticSearch', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12005, 'Power Automate', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12006, 'Power Apps', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12007, 'Dynamics CRM', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12008, 'Dynamics AX', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12009, 'Sharepoint', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12010, 'Salesforce', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12011, 'Adobe Experience Manager', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12012, 'UIPath', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12013, 'BluePrism', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12014, 'Mulesoft', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12015, 'Wordpress', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12016, 'Drupal', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12017, 'Joomla', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12018, 'Sitecore', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12019, 'Pimcore', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12020, 'Ruby On Rails', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12021, 'Django', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12022, 'Flask', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12023, 'Laravel', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12024, 'Magento', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12025, 'Liferay', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12026, 'Alfresco', '', 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12027, 'Cypress', '', 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12028, 'Fiddler', '', 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12029, 'Cucumber', '', 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12030, 'Sketch', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12031, 'Zeplin', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12032, 'Illustrator', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12033, 'Photoshop', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12034, 'Figma', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12035, 'InVision', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12036, 'XD', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12037, 'After Effects', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12038, 'Appium Server', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12039, 'Appium Inspector', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12040, 'Charles Proxy', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12041, 'Mockoon', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12042, 'Zephyr Squad', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12043, 'SauceLab', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12044, 'EasyRepro', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12045, 'BrowserStack', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12046, 'TestRail', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12047, 'Extent Reports', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12048, 'Robot Framework', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12049, 'Katalon Studio', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (12050, 'Microfocus ALM', NULL, 'HARD', 12, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13001, 'Git', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13002, 'SVN', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13003, 'CVS', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13004, 'Mercurial', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13005, 'Serena Dimensions', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (13006, 'TFS', NULL, 'HARD', 13, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14001, 'Abstract Factory', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14002, 'Builder', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14003, 'Factory method', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14004, 'Prototype', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14005, 'Singleton', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14006, 'Adapter', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14007, 'Bridge', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14008, 'Composite', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14009, 'Decorator', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14010, 'Facade', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14011, 'Flyweight', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14012, 'Proxy', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14013, 'Chain of responsability', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14014, 'Command', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14015, 'Interpreter', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14016, 'Iterator', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14017, 'Mediator', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14018, 'Memento', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14019, 'Observer', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14020, 'State', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14021, 'Strategy', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14022, 'Template', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14023, 'Visitor', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14024, 'Active object', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14025, 'Lock', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14026, 'Join', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14027, 'Monitor', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14028, 'Proactor', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14029, 'Reactor', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14030, 'Scheduler', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14031, 'Thread pool', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14032, 'Interceptor', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14033, 'MVC', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14034, 'n-tier', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14035, 'Specification', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14036, 'Publish-Subscribe', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14037, 'Service locator', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14038, 'Active record', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14039, 'Identity Map', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14040, 'DAO', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14041, 'DTO', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14042, 'Inversion of Control', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14043, 'Blackboard', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14044, 'Business delegate', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14045, 'Composite entity', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14046, 'Dependency Injection', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14047, 'Lazy loading', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14048, 'Mock object', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14049, 'Null object', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14050, 'Object pool', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14051, 'Servant', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14052, 'Twin', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14053, 'SOLID principles', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14054, 'TDD', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14055, 'FDD', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14056, 'DDD', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14057, 'Microservices architecture', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14058, 'Saga', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14059, 'API composition', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14060, 'CQRS', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14061, 'Domain event', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14062, 'Event sourcing', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14063, 'Remote Procedure Invocation', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14064, 'API Gateway', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14065, 'Service discovery', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14066, 'Circuit Breaker', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14067, 'Access Token', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14068, 'Log aggregation', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14069, 'Distributed tracing', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14070, 'MVP', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14071, 'MVVM', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (14072, 'MVI', NULL, 'HARD', 14, 6);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15001, 'Kanban', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15002, 'eXtreme Programming', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15003, 'Scaled Agile Framework (SAFe)', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15004, 'Large-Scale Scrum (LeSS)', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15005, 'Lean Development', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15006, 'Design Thinking', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15007, 'Six Sigma', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15008, 'PMBOK', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15009, 'PMI', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15010, 'PRINCE 2', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15011, 'Scrum', NULL, 'HARD', 15, 7);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15012, 'Asana', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15013, 'Trello', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15014, 'Remedy', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15015, 'Confluence', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15016, 'Bamboo', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (15017, 'Jira', NULL, 'HARD', 15, 5);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16001, 'Assertività', 'La capacità di esprimere in modo chiaro ed efficace le proprie emozioni, opinioni,bisogni e punti di vista, senza ledere quelle altrui', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16002, 'Autostima', 'La valutazione e apprezzamento di se stessi, tramite l''autoapprovazione del proprio valore personale', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16003, 'Autoefficacia', 'La consapevolezza di esser capaci di fare, sentire, esprimere, essere o divenire qualcosa', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16004, 'Consapevolezza', 'La capacità di essere a conoscenza di ciò che viene percepito e delle proprie risposte comportamentali', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16005, 'Ascolto attivo', 'Saper ascoltare con un elevato grado di attenzione e partecipazione comunicativa. Saper osservare bene l''interlocutore, percependo anche il suo linguaggio non verbale e paraverbale', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16006, 'Intelligenza emotiva', 'Saper riconoscere, identificare ed etichettare nel modo appropriato e gestire le proprie emozioni e quelle degli altri, allo scopo di raggiungere determinati obiettivi', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16007, 'Empatia', 'La capacità di riconoscere le emozioni degli altri come se fossero proprie, calandosi nella realtà altrui per comprenderne punti di vista, pensieri, sentimenti, emozioni', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16008, 'Flessibilità', 'La capacità di adattamento a situazioni impreviste, al cambiamento', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16009, 'Negoziazione', 'Saper risolvere le divergenze, raggiungendo un compromesso o un accordo evitando discussioni e controversie', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16010, 'Gestione dei conflitti', 'Saper limitare gli aspetti negativi di un conflitto, aumentandone al contempo gli aspetti positivi e costruttivi', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16011, 'Resilienza', 'La capacità di affrontare e superare un evento traumatico o un periodo di difficoltà', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16012, 'Resistenza allo stress', 'L''essere in grado di reagire positivamente alla pressione lavorativa mantenendo il controllo, rimanendo focalizzati sulle priorità, senza trasferire sui colleghi le proprie eventuali tensioni', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16013, 'Problem solving', 'La serie di attività di risoluzione di un problema che sono dinamiche (richiedono delle prime azioni da svolgere nell''ambiente, a partire dalle quali sono poi prese successive decisioni), dipendenti dal tempo (le decisioni devono essere prese al momento giusto in relazione all''ambiente) e complesse (la maggior parte delle variabili non sono correlate l''una all''altra)', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16014, 'Pensiero laterale', 'La modalità di risoluzione di problemi logici che prevede un approccio indiretto, l''osservazione del problema da diverse angolazioni, contrapposta alla tradizionale modalità che prevede concentrazione su una soluzione diretta del problema', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16015, 'Pensiero analitico', 'L''abilità di pensare in maniera dettagliata, approfondita e sistematica per risolvere dei problemi', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16016, 'Pensiero critico', 'La capacità di pensare in modo chiaro e razionale, comprendendo la connessione logica tra le idee', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16017, 'Concentrazione', 'La capacità volontaria di fissare il pensiero su un oggetto, sul compimento di un gesto, un''azione predeterminata ed elaborata dalla propria mente, o semplicemente su un argomento specifico', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16018, 'Brainstorming', 'La capacità di  far emergere idee volte alla risoluzione di un problema', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16019, 'Attitudine di vendita', 'La capacità di sviluppare strategie funzionali all''individuazione della giusta soluzione per problemi complessi dei clienti, generando al contempo entusiasmo per la soluzione che viene proposta, favorendo l''impegno delle parti coinvolte', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16020, 'Pianificazione', 'Il riuscire a pensare al futuro, per anticipare mentalmente il modo corretto di eseguire un compito. Il saper selezionare delle attività necessarie a raggiungere un obiettivo, il saperne decidere l''ordine e il saper creare un piano', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16021, 'Gestione del tempo', 'Il saper strutturare in maniera sistematica l''allocazione temporale e la distribuzione di richieste concorrenti, basandosi su priorità', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16022, 'Creatività', 'La capacità di rprodurre idee nuove, insolite, in maniera abbondante, percorrendo fino alla fine una strada ideativa con ricchezza di particolari, selezionando le idee e organizzandole in forme nuove', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16023, 'Leadership', 'La capacità di far leva sulla consapevolezza di se, sulla gestione delle proprie emozioni, sulla comprensione dei sentimenti degli altri, sulla possibilità di creare risonanza, al fine di motivare un gruppo di persone ad agire alla ricerca di un obiettivo comune', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16024, 'Gestione del team', 'Il saper coordinare un gruppo di persone al fine dello svolgimento di un compito con spirito positivo, sviluppando al tempo stesso il senso di responsabilità e potenziando le capacità professionali delle persone stesse', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16025, 'Collaborazione', 'L''essere in grado di partecipare attivamente al compimento di un lavoro o allo svolgimento di una attività', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16026, 'Delega', 'La capacità di individuare una persona compatibile, per competenza e profilo, verso una responsabilità lavorativa e, successivamente, di attuare, in maniera partecipata, un passaggio di responsabilità verso quella persona', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16027, 'Coaching', 'La capacità di accompagnare una persona verso una definizione dei risultati che desidera raggiungere, una comprensione delle sue motivazioni, verso il riconoscimento di se stesso, l''individuazione delle proprie competenze, verso il compimento di azioni necessarie a conseguire il raggiungimento dei risultati individuati e di stimolare l''apprendimento continuo tramite l''esperienza', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16028, 'Tutoring', 'La capacità di aiutare e sostenere delle persone durante il processo di apprendimento, in modo interattivo, intenzionale e sistematico', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16029, 'Team building', 'L''essere in grado di individuare, progettare e realizzare attività e procedimenti, formativi o educativi, per far interagire un gruppo di persone allo scopo di migliorarne la capacità di lavorare in squadra', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16030, 'Responsabilità', 'L''essere affidabile. Il riuscire a portare a termine dei compiti ricevuti, il rispettare tempistiche e priorità con disciplina, dimostrando attenzione alle esigenze organizzative', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16031, 'Fornire feedback', 'La capacità di formulare un feedback in maniera corretta e specifica, in riferimento a comportamenti e non a persone, evidenziando le conseguenze del comportamento e cercando delle azioni di miglioramento', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16032, 'Accettazione dei feedback', 'La capacità di cogliere in maniera positiva i significati di un feedback, sia positivo che negativo. L''essere in grado di intraprendere azioni migliorative in seguito ad un feedback e la propensione alla ricerca di feedback', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16033, 'Public speaking', 'L''essere in grado di eseguire un discorso dal vivo, faccia a faccia, davanti ad un pubblico di ascoltatori, in maniera chiara, positiva, coinvolgente, controllando le proprie ansie e le proprie preoccupazioni, gestendo l''eventuale noia del pubblico, trasferendo in maniera efficace il contenuto del discorso', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16034, 'Storytelling', 'L''essere in grado di utilizzare l''arte della narrazione, del racconto, sia in forma orale che scritta, per comunicare in maniera efficace e coinvolgente i propri prodotti o i propri servizi', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16035, 'Business writing', 'Il saper organizzare e decidere il contenuto, il saper scegliere le parole da usare, il saper modulare il linguaggio all''interno di un testo, allo scopo di raggiungere degli obiettivi di business', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (16036, 'Networking', 'La capacità di creare e gestire una rete di contatti, con il proposito di costruire delle relazioni di valore con persone con cui si ha un obiettivo in comune', 'SOFT', 16, 8);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17001, 'Italiano', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17002, 'Inglese', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17003, 'Francese', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17004, 'Spagnolo', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17005, 'Portoghese', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17006, 'Russo', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17007, 'Tedesco', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17008, 'Hindi', NULL, 'SOFT', 17, 9);
INSERT INTO skill (ID, NAME, DESCRIPTION, TYPE, AreaId, ScaleId) VALUES (17009, 'Arabo', NULL, 'SOFT', 17, 9);
